# Generated by Django 5.2.5 on 2025-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
